### ISSUE TITLE
ec2-mac-utils missing from AMIs and AWS Homebrew tap

### ISSUE THREAD

**Issue by thimslugga** [aws/ec2-macos-utils#1]
> The utility will be installed by default for all AMIs vended by AWS after December 8, 2021. ec2-macos-utils is also available as a cask for install and updates via [AWS' Homebrew tap](https://github.com/aws/homebrew-aws).

The readme mentions the tool should be installed by default on the EC2 Mac AMIs and/or available in the AWS Homebrew tap but this doesn't appear to be the current situation.

https://github.com/aws/homebrew-aws

**Comment by jahkeup** [comment]
Thanks for creating this issue @thimslugga :)

I agree with you - this should be distributed and able to be updated via Homebrew.

I'll chat with the team to get the ball rolling!

**Comment by jahkeup** [comment]
Added to tap in https://github.com/aws/homebrew-aws/pull/24

The package will be available in an upcoming AMI release :)
